remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer
  - Software Developer
  - Programmer
  - CI/CD

locations:
  - Boston


apply_once_at_company: true

distance: 50

company_blacklist:
  - Cisco

title_blacklist:
  - VR
  - AR

location_blacklist:
  - Canada
  - Mexico


job_applicants_threshold:
  min_applicants: 0
  max_applicants: 1

llm_model_type: openai
llm_model: 'gpt-4o-mini'
llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
